version: '3'
services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service #подключаем нашу локальную папку, к докер контейнеру. для того что бы все изменения в коде вносимые локально сразу же подгружались в докер контейнер
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"       

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - pg-data:/var/lib/postgresql/data
    #ports:
      #- "5432:5432"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A weather_parser.app worker --beat --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass


  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A weather_parser.app flower
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  pg-data:





      #c помощью command выполняем команду для запуска сервера джанго ('sh -c' является shell linux)
# c помощью depends_on установим зависимость сервисов depends_on = database означает что сервис web-app зависит от сервиса database, и web-app не запуститься раньше чем database