# Generated by Django 3.2.16 on 2023-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('temp_max', models.CharField(max_length=100)),
                ('temp_min', models.CharField(max_length=100)),
                ('weather_description', models.CharField(max_length=100)),
            ],
        ),
    ]
