# Generated by Django 3.2.16 on 2023-12-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
